DROP TABLE MENU;
CREATE TABLE MENU(

MNO NUMBER,
NAME VARCHAR2(255) NOT NULL,
PRICE NUMBER NOT NULL

);
ALTER TABLE MENU
ADD CONSTRAINT MENU_PK PRIMARY KEY(MNO);
--------------------------------------------------------------------------------------------------------------
DROP TABLE CUSTOMER;
CREATE TABLE CUSTOMER(

CNO NUMBER,
NAME VARCHAR2(255),
EMAIL VARCHAR2(100)

);
ALTER TABLE CUSTOMER
ADD CONSTRAINT CUSTOMER_PK PRIMARY KEY(CNO);

ALTER TABLE CUSTOMER
ADD CONSTRAINT CUSTOMER_UK UNIQUE(EMAIL);
-----------------------------------------------------------------------------------------------------------
DROP TABLE TEE_ORDER;
CREATE TABLE TEE_ORDER(

TNO NUMBER,
ORERERED_AT TIMESTAMP NOT NULL,
MNO NUMBER NOT NULL,
QUANTITY NUMBER DEFAULT 1,
CNO NUMBER NOT NULL,
CONSTRAINT TEE_ORDER_PK PRIMARY KEY(TNO),
CONSTRAINT MENU_TEE_ORDER_FK FOREIGN KEY(MNO) REFERENCES MENU(MNO),
CONSTRAINT CUSTOMER_TEE_ORDER_FK FOREIGN KEY(CNO) REFERENCES CUSTOMER(CNO)

);
---------------------------------------------------------------------------------------------------------------------------------------
--시퀀스

CREATE SEQUENCE SEQ_MENU START WITH 101 INCREMENT BY 1;
INSERT INTO MENU(MNO, NAME, PRICE) VALUES (SEQ_MENU.NEXTVAL, '아이스아메리카노', 2000);
SELECT SEQ_TEE_ORDER.CURRVAL FROM DUAL;

INSERT INTO MENU VALUES(SEQ_MENU.NEXTVAL,'아이스초코',3500);
INSERT INTO MENU VALUES(SEQ_MENU.NEXTVAL,'민트초코', 4000);
INSERT INTO MENU VALUES(SEQ_MENU.NEXTVAL, '아이스티', 3000);
INSERT INTO MENU VALUES(SEQ_MENU.NEXTVAL,'아이스바닐라라떼', 4500);
INSERT INTO MENU VALUES(SEQ_MENU.NEXTVAL, '타로버블티' , 5000);
INSERT INTO MENU VALUES(SEQ_MENU.NEXTVAL, '자바칩플렛치노',5500);
INSERT INTO MENU VALUES(SEQ_MENU.NEXTVAL, '고구마 라떼',5000);
INSERT INTO MENU VALUES(SEQ_MENU.NEXTVAL,'티라미수',6000);

SELECT * FROM MENU;
COMMIT;


CREATE SEQUENCE SEQ_CUSTOMER START WITH 1001 INCREMENT BY 1;
--컬럼 명을 생략해서 데이터 삽입 가능 :컬럼명을 확인하여 컬럼 순서대로 모두 값을 입력
INSERT INTO CUSTOMER VALUES (SEQ_CUSTOMER.NEXTVAL, '몽여름','TEST01@TEST.COM');
INSERT INTO CUSTOMER (NAME, EMAIL, CNO) VALUES('김수현','TEST02@TEST.COM', SEQ_CUSTOMER.NEXTVAL);
SELECT * FROM CUSTOMER;

CREATE SEQUENCE SEQ_TEE_ORDER START WITH 1 INCREMENT BY 1;
INSERT INTO TEE_ORDER VALUES(SEQ_TEE_ORDER.NEXTVAL,SYSTIMESTAMP, 161, 1, 1061);
INSERT INTO TEE_ORDER VALUES(SEQ_TEE_ORDER.NEXTVAL,SYSTIMESTAMP, 162, 1, 1061);
INSERT INTO TEE_ORDER VALUES(SEQ_TEE_ORDER.NEXTVAL,SYSTIMESTAMP,163,2,1061);

SELECT * FROM TEE_ORDER;

DROP SEQUENCE SEQ_T;
create sequence seq_t start with 1 increment by 1;
SELECT SEQ_T.NEXTVAL AS "시퀀스 발행번호", SEQ_T.CURRVAL "마지막 시퀀스번호" FROM DUAL;
--select seq_t.currval from dual;


--DML : CRUD

DESC MENU;
SELECT NAME , PRICE   FROM MENU;
SELECT NAME 메뉴이름 FROM MENU;
SELECT  * FROM MENU;

INSERT INTO MENU VALUES(SEQ_MENU.NEXTVAL, '아이스고구마 라떼', 30000);
COMMIT;

--데이터 수정(조건절을 사용하여 특정 행을 지정 해야하며 그러지않을 경우 전체 행이 변경)
UPDATE MENU 

SET PRICE=3000, NAME='감자라떼'

WHERE MNO=170;


delete MENU

WHERE MNO=170;


SELECT * FROM TEE_ORDER;

--CASCADE : 종속된 객체까지 영향을 끼친다. (연결된 ㅈ
DELETE MENU
WHERE MNO = 171;

ALTER TABLE TEE_ORDER
DROP CONSTRAINT MENU_TEE_ORDER_FK;

ALTER TABLE TEE_ORDER
ADD CONSTRAINT MENU_TEE_ORDER_FK FOREIGN KEY(MNO) REFERENCES MENU(MNO) ON DELETE  CASCADE;

ROLLBACK;

SELECT * FROM MENU;
SELECT * FROM TEE_ORDER;

DROP TABLE MENU CASCADE CONSTRAINTS ; 
-- 삭제 방법
--외래키 삭제 후 삭제 가능
--종속된 테이블을 먼저 삭제 (외래키가 같이 삭제) 삭제 가능 

