-- USER 생성

--CREATE USER 아이디 IDENTIFIED BY 비밀번호; -->아이디 생성
CREATE USER C##TEST01 IDENTIFIED BY 1234;
--DROP USER C##TEST01; ->아이디 삭제
DROP USER C##TEST01;

--C## 없이 사용자 계정 생성 방법
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

CREATE USER TEST01 IDENTIFIED BY 1234;

DROP USER TEST01 ;

--접속 권한
--SESSION : 접속을 관리하는 것들
--Privilege_권한 :바로 반영 가능
GRANT CREATE SESSION TO TEST01;
GRANT CREATE table TO TEST01;
REVOKE CREATE table FROM TEST01;

--role_역할 : 재접속 후 반영 가능
GRANT RESOURCE, DBA, CONNECT TO TEST01;

SELECT * FROM DBA_ROLE_PRIVS where grantee='TEST01';
SELECT * FROM DBA_SYS_PRIVS where grantee='TEST01';
--접속 권한 해제: REVOKE
--------------------------------------------------------------------------------

create user green identified by 1234;

GRANT CONNECT, RESOURCE,UNLIMITED TABLESPACE TO GREEN;
REVOKE CREATE SESIION, CREATE TABLE FORM GREEN;

SELECT * FROM DBA_ROLE_PRIVS where grantee='GREEN';
SELECT * FROM DBA_SYS_PRIVS where grantee='GREEN';

SELECT ROLE, PRIVILEGE FROM ROLE_SYS_PRIVS WHERE ROLE='DBA';
SELECT ROLE, PRIVILEGE FROM ROLE_SYS_PRIVS WHERE ROLE='RESOURCE';
SELECT ROLE, PRIVILEGE FROM ROLE_SYS_PRIVS WHERE ROLE='CONNECT';




